#!/usr/bin/env bash

echo Building discovery-server...
cd discovery-server; gradle --daemon clean build distdocker; cd -

echo Building edge-server...
cd edge-server; gradle --daemon clean build distdocker; cd -

echo Building message-listener...
cd message-listener; gradle --daemon clean build distdocker; cd -

echo Building monitor-dashboard...
cd monitor-dashboard; gradle --daemon clean build distdocker; cd -

echo Building consultant-service...
cd consultant-service; gradle --daemon clean build distdocker; cd -

echo Building unit-service...
cd unit-service; gradle --daemon clean build distdocker; cd -

echo Building customer-service...
cd customer-service; gradle --daemon clean build distdocker; cd -

echo Building contract-service...
cd contract-service; gradle --daemon clean build distdocker; cd -

echo Building assignment-service...
cd assignment-service; gradle --daemon clean build distdocker; cd -

echo Building unitside-composite-service...
cd unitside-composite-service; gradle --daemon clean build distdocker; cd -

echo Building customerside-composite-service...
cd customerside-composite-service; gradle --daemon clean build distdocker; cd -

echo Building person-api-service...
cd person-api-service; gradle --daemon clean build distdocker; cd -

echo Building person-service...
cd person-service; gradle --daemon clean build distdocker; cd -

echo Building turbine...
cd turbine; gradle --daemon clean build distdocker; cd -

#find . -name *SNAPSHOT.jar -exec du -h {} \;
